### PR TITLE
Update player version to fix IE Promise failure

### PR DESCRIPTION
**Pull request by mereskin**

### CODE REVIEW

**Comment by mereskin** [comment]
cc/ @ThrivingKings - that should fix IE issue w/ Promise.

Either fetch SDK from this branch or merge into master and then do `npm link` locally.

**Comment by possibilities** [comment]
@ThrivingKings, if you validate it feel free to merge also. I won't
complain (:

**Comment by rjz** [comment]
(unless there's a good reason to inline the dep, though, let's keep it in `bower.json`?)

**Comment by mereskin** [comment]
Should be good now. Please, triage.

**Comment by ThrivingKings** [comment]
This checks out for me but would love some additional eyes to confirm

**Comment by possibilities** [comment]
Master should work but the great unwashed masses will be installing from npm so since it works for you  I'd rather risk it, move fast, and potentially break master than not.

**Comment by mereskin** [comment]
Thanks, Mike

**Comment by mereskin** [comment]
Worth publishing 1.7.2?

**Comment by possibilities** [comment]
Let's dogfood it until next week.

**Pull request merged**
